package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.dockerCommand
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'build_1'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("build_1")) {
    expectSteps {
        dockerCommand {
            name = "build teamcity-server:latest-nanoserver-1903"
            commandType = build {
                source = file {
                    path = "context/generated/windows/Server/nanoserver/1903"
                }
                contextDir = "context"
                namesAndTags = "teamcity-server:latest-nanoserver-1903"
                commandArgs = "--pull"
            }
            param("dockerImage.platform", "windows")
        }
        dockerCommand {
            name = "build teamcity-minimal-agent:latest-nanoserver-1903"
            commandType = build {
                source = file {
                    path = "context/generated/windows/MinimalAgent/nanoserver/1903"
                }
                contextDir = "context"
                namesAndTags = "teamcity-minimal-agent:latest-nanoserver-1903"
                commandArgs = "--pull"
            }
            param("dockerImage.platform", "windows")
        }
        dockerCommand {
            name = "build teamcity-agent:latest-windowsservercore-1903"
            commandType = build {
                source = file {
                    path = "context/generated/windows/Agent/windowsservercore/1903"
                }
                contextDir = "context"
                namesAndTags = "teamcity-agent:latest-windowsservercore-1903"
                commandArgs = "--pull"
            }
            param("dockerImage.platform", "windows")
        }
        dockerCommand {
            name = "build teamcity-agent:latest-nanoserver-1903"
            commandType = build {
                source = file {
                    path = "context/generated/windows/Agent/nanoserver/1903"
                }
                contextDir = "context"
                namesAndTags = "teamcity-agent:latest-nanoserver-1903"
                commandArgs = "--pull"
            }
            param("dockerImage.platform", "windows")
        }
    }
    steps {
        items.removeAt(0)
        items.removeAt(0)
        items.removeAt(0)
    }
}
